### ISSUE TITLE
can't make deploy due to bitbucket import

### ISSUE THREAD

**Issue by yuvalShalgi227** [getsocial-rnd/ecs-drain-lambda#1]
when tryign to get deploy i get 
cannot find package "bitbucket.org/getsocial/ecs-drain-lambda" in any of:
        /usr/local/go/src/bitbucket.org/getsocial/ecs-drain-lambda (from $GOROOT)

why is there a dependcy in bitbucket ?

**Comment by Trane9991** [comment]
Ops, sorry. This is from our old private repo, where we kept the code before it went OpenSource.
Will push the fix in a moment.

**Comment by Trane9991** [comment]
@yuvalShalgi227, done. Can you pull the changes and try again, please?

**Comment by yuvalShalgi227** [comment]
Thanks @Trane9991 , its working great now. you guys rock!
note i had to run go get github.com/aws/aws-lambda-go/lambda and go get github.com/getsocial-rnd/ecs-drain-lambda before it could run
