### ISSUE TITLE
GetClusterNameFromInstanceUserData does not find ecs cluster name

### ISSUE THREAD

**Issue by yuvalShalgi227** [getsocial-rnd/ecs-drain-lambda#2]
hello, 
My cluster has userdata we added, as a result ecs-drain-lambda  can't find clustername and can't drain the instance.
can you perhaps explain the assumptions that GetClusterNameFromInstanceUserData uses ? i am willing to make changes to my userdata

**Comment by Trane9991** [comment]
Hey :) 

actually, it is present in the readme.

Lambda checks the user data for value like `ECS_CLUSTER=my_cluster_name` with the following regexp `regexp.MustCompile(`ECS_CLUSTER=(\S*)`)` [code here](https://github.com/getsocial-rnd/ecs-drain-lambda/blob/master/ecs.go#L20)

How your UserData looks?

**Comment by Trane9991** [comment]
This is the default approach for ECS Agent configurations, you can see from [this link](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html), that ECS Agent looks for the `ECS_CLUSTER` environment variable.

**Comment by Trane9991** [comment]
CloudFormation example from the [official docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-ecs.html#quickref-ecs-example-1.yaml):
```
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource ECSAutoScalingGroup --region ${AWS::Region}
```

**Comment by yuvalShalgi227** [comment]
checked and my ecs.config does have the cluster name as ECS_CLUSTER=
only thing i can think of is since it's in the metadata of the LaunchTemplate GetClusterNameFromInstanceUserData can find it, will add an env avr in the userdata it self.
might take me a while to get back to you that it really works.

**Comment by Trane9991** [comment]
@yuvalShalgi227 Instance template shouldn't matter.

You checked the resulted ecs.config?
You need to look into the UserData itself, the command which supposed to add `ECS_CLUSTER=` into the ecs.config.

Can you hide the sensitive info and share you share your UserData with me?

**Comment by yuvalShalgi227** [comment]
Hello trane, can't really share my userdata at the moment.
indeed the userdata does not have such a command, it take place in the metadata (gets the data to the ecs.config)
so i wil just add "export ECS_CLUSTER=", {"Ref": "ECSCluster"},"\n", to the template that holds the userdata.
might take me a while to check (unrealted to this issue) should be able to update next week.
thanks

**Comment by yuvalShalgi227** [comment]
after adding the export ECS_CLUSTER= it's working !
thanks again :)
