### ISSUE TITLE
Region specific

### ISSUE THREAD

**Issue by nitrocode** [getsocial-rnd/ecs-drain-lambda#5]
Hi. I noticed that if I want to drain ecs clusters in a different region than `us-east-1`, I have to change the `provider.region` key in `serverless.yml`.

It's possible to feed in the `--region` argument to `sls` like so

```
sls deploy -v --region us-west-2
```

if `serverless.yml` contains

```
provider:
  region: ${opt:region}
```

**Comment by Trane9991** [comment]
Hey, according to the [docs](https://www.serverless.com/framework/docs/providers/aws/cli-reference/deploy/), the custom region can be provided even without the `${opt:region}`, but I didn't actually try that.

I'm pretty sure it should overwrite the `region` provided in the `serverless.yml`, but can be sure without trying :) 

Can you try and let me know? Thanks!

**Comment by nitrocode** [comment]
Ah interesting. I do see the switch here.

```
✗ sls deploy --help
Plugin: Deploy
deploy ........................ Deploy a Serverless service
deploy function ............... Deploy a single function from the service
deploy list ................... List deployed version of your Serverless Service
deploy list functions ......... List all the deployed functions and their versions
    --conceal .......................... Hide secrets from the output (e.g. API Gateway key values)
    --stage / -s ....................... Stage of the service
    --region / -r ...................... Region of the service
```

Most of our stuff is in `us-west-2` so I was thinking that the lambda didn't work correctly when I had deployed it as-is in `us-east-1`. At the very least, the fact that the serverless deploy defaults to `us-east-1` could be added to the `README.md` with a note suggesting to use `sls deploy --region` for different regions.

**Comment by Trane9991** [comment]
Sure, will do
